global_frame: summit_xl_a_odom
rolling_window: true

width: 5
height: 5

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}